# Generated by Django 4.0.6 on 2026-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourTrekking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trek_date', models.DateField()),
                ('weekday', models.CharField(blank=True, max_length=128, null=True)),
                ('meeting_type', models.CharField(blank=True, max_length=128, null=True)),
                ('meeting_type_id', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('companion1', models.CharField(blank=True, max_length=128, null=True)),
                ('companion2', models.CharField(blank=True, max_length=128, null=True)),
                ('companion3', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yourtrekking',
                'managed': False,
            },
        ),
    ]
