# Generated by Django 3.2 on 2026-05-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourtrekking',
            options={'managed': False},
        ),
    ]
