# Generated by Django 3.2 on 2026-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0002_alter_yourtrekking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourtrekking',
            options={'managed': True},
        ),
    ]
